### ISSUE TITLE
Mac: QDialogButtonBox button enabled state changes does not redraw the button

### ISSUE THREAD

**Issue by bmiller** [3ll3d00d/beqdesigner#56]
The QDialogButtonBoxes do not redraw their buttons when the enabled state of one of the buttons changes in it.  For example in add signal when a preview is generated the "OK" button still appears to be disabled.  Switching to another window/app and back to force a window redraw results in the correct display.  

This is only a drawing issue.  The button is still able to be clicked on and have it's action triggered. 

It also appears to only be for enable/disable.  Changing the buttons title causes a redraw and the new title is displayed.  

QPushButton buttons are not affected by this.  They redraw as expected.

**Comment by bmiller** [comment]
I'm looking into a fix for this one.  It's my first time using QT and I'm learning how it works still.  I'm wondering if it might be a bug in QT for QDialogButtonBox with the behavior I'm seeing.

**Comment by 3ll3d00d** [comment]
that does sound odd

is it on a particular screen or happens to all of them?

**Comment by bmiller** [comment]
It happens on both the QDialogButtonBox in both the extract and signal dialogs.  I haven't checked if there are any others yet.  The signal one is where I noticed that it was clickable but still drawn inactive unless the entire window gets a redraw.  In extract while the process is running it's not clickable but still appears to be.  When the extract is done the name changes and it's working as expected.  

In prepare_signal() if I call repaint on the button then it redraws as expected:
```
        button = self.__dialog.buttonBox.button(QDialogButtonBox.Ok)
        button.setEnabled(True)
        button.repaint(button.rect())

```

So I'm leaning towards it being a QT bug.  This workaround works but that's ugly to do everywhere.  I'm still looking into a better solution.  What seems weird is I'm not finding anything on other people running into it.

**Comment by 3ll3d00d** [comment]
I guess it could also be a pyqt5 bug

I should switch to pyside2 (the new official Qt for python bindings) at some point though iirc some other dependency needs to update first (forget which one). This could rule out the python bindings at least

**Comment by 3ll3d00d** [comment]
One option might be to monkey patch setEnabled to also call repaint, obviously a hack but at least it just is hacked once

**Comment by bmiller** [comment]
Yeah, I thought of going that route too.  It was something I was going to look up today.  Being new to python I haven't done it before.  I don't want to get too hacky though since right now it's only for me.  I'm thinking of living with the issue for now since it's not a show stopper and I'm aware of it.  If more mac users (or others) start using it then  we can add the hack fix.  In the meantime QT or pyqt5 might get an update that fixes it.

**Comment by 3ll3d00d** [comment]
seems like this was largely fixed by qt upgrade so closing

**Comment by bmiller** [comment]
Sorry, didn't realize this was still open.  The QT upgrade fixed most of it and running in dark mode fixes the other issues.  So it was good to close. 👍

**Comment by EfremBraun** [comment]
Just FYI, this issue is known by the Qt developers. It still exists on both PySide2 and PyQt5. See https://bugreports.qt.io/browse/PYSIDE-695.
